version: "3"

services:

  api: 
    container_name: capstone_q4_container
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./src:/app/src
    expose:
    - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn dev'

  pg:
    container_name: postgres-capstone
    image: postgres:14.2-alpine
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432        
