import {MigrationInterface, QueryRunner} from "typeorm";

export class firstcommit1651093247097 implements MigrationInterface {
    name = 'firstcommit1651093247097'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP CONSTRAINT "user_surgery_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP CONSTRAINT "user_surgery_surgery_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP CONSTRAINT "user_surgery_surgery_detail_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP CONSTRAINT "anamnesis_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_doctor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "doctors_address_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "doctors_user_id_fkey"`);
        await queryRunner.query(`CREATE TABLE "userAllergies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying(350), "userId" uuid NOT NULL, "allergyId" uuid NOT NULL, CONSTRAINT "UQ_70439464cf351f1780b4e855f0f" UNIQUE ("userId", "allergyId"), CONSTRAINT "PK_1ed1340221ac0eaa9629c6f41ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "UserDiseases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying(250), "medication" character varying(250), "userId" uuid, "diseaseId" uuid, CONSTRAINT "UQ_098619902905894a214fe89f2b7" UNIQUE ("userId", "diseaseId"), CONSTRAINT "PK_8dbe1897811768e2f5b17e822d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "userMedications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying(350), "userId" uuid NOT NULL, "medicationId" uuid NOT NULL, CONSTRAINT "UQ_70761d2c0bbd96c7ae9dc2b9cbc" UNIQUE ("userId", "medicationId"), CONSTRAINT "PK_0e43ad1544c8364c4ef9fde1c8d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "surgery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_2e963fc0e35d07a36e15f331754" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vaccine" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_3879829f8d2e396157ebffab918" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_vaccine" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying, "date" TIMESTAMP NOT NULL, "dose" integer, "vaccine_id" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "UQ_14914d9ad00a11315bfe9dbf1c5" UNIQUE ("userId", "vaccine_id"), CONSTRAINT "PK_29d686068f737824f9ce09da0ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profileImage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "url" character varying NOT NULL, "key" character varying NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "REL_5f1aea3730b5a2a4600bd7ff66" UNIQUE ("userId"), CONSTRAINT "PK_9d401e89e415fc9ae4313dcf7ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP COLUMN "surgery_detail_id"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "continous_medication"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "drug_user"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "physical_activity"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP CONSTRAINT "anamnesis_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "birth_date"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "doctor_id"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "address_id"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD "date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "continuousMedication" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "drugUser" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "physicalActivity" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD CONSTRAINT "UQ_c5b75666b93238b503aba9fcf32" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "birthDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "doctorId" uuid`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "sex" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "addressId" uuid`);
        await queryRunner.query(`ALTER TABLE "allergies" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "diseases" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "diseases" DROP CONSTRAINT "diseases_name_key"`);
        await queryRunner.query(`ALTER TABLE "diseases" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "diseases" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "diseases" ADD CONSTRAINT "UQ_293ca0c5bba4f9950f3fb976d33" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "medications" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "medications" DROP CONSTRAINT "medications_name_key"`);
        await queryRunner.query(`ALTER TABLE "medications" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "medications" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "medications" ADD CONSTRAINT "UQ_4c71a8a6de0a811702d1ef8d73f" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "gender" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "sex"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "sex" character varying`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "description" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "UQ_62069f52ebba471c91de5d59d61" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "phone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "street" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "number" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "district"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "district" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "city" character varying(250)`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "complement" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD CONSTRAINT "UQ_142ca675cea1a426abac7ba2376" UNIQUE ("userId", "surgery_id")`);
        await queryRunner.query(`ALTER TABLE "userAllergies" ADD CONSTRAINT "FK_5880801a70cbda1b56a04eb07fe" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userAllergies" ADD CONSTRAINT "FK_de7a18a07034d48eb6b2d5cec26" FOREIGN KEY ("allergyId") REFERENCES "allergies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserDiseases" ADD CONSTRAINT "FK_47fd2b1a5aed5759cbda6b0f6b0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserDiseases" ADD CONSTRAINT "FK_c5306c28d972032b84309267399" FOREIGN KEY ("diseaseId") REFERENCES "diseases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userMedications" ADD CONSTRAINT "FK_cfaf05e2b6d8b08d2f9e5ef1802" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userMedications" ADD CONSTRAINT "FK_bdaff5385ad51bcc1af4848a5ed" FOREIGN KEY ("medicationId") REFERENCES "medications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD CONSTRAINT "FK_512b1bdb900e45a758e2dbb49df" FOREIGN KEY ("surgery_id") REFERENCES "surgery"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD CONSTRAINT "FK_5f7f92a4446c70b2a7ce84994b0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vaccine" ADD CONSTRAINT "FK_cc3e88ea2a405280a5b6d09caba" FOREIGN KEY ("vaccine_id") REFERENCES "vaccine"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_vaccine" ADD CONSTRAINT "FK_44987c7db9c6c92fa2e8c310461" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD CONSTRAINT "FK_c5b75666b93238b503aba9fcf32" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profileImage" ADD CONSTRAINT "FK_5f1aea3730b5a2a4600bd7ff66e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_0c1af27b469cb8dca420c160d65" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_01733651151c8a1d6d980135cc4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "FK_ad816aa66aa42fad408b1b7d762" FOREIGN KEY ("addressId") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "FK_ad816aa66aa42fad408b1b7d762"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_01733651151c8a1d6d980135cc4"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_0c1af27b469cb8dca420c160d65"`);
        await queryRunner.query(`ALTER TABLE "profileImage" DROP CONSTRAINT "FK_5f1aea3730b5a2a4600bd7ff66e"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP CONSTRAINT "FK_c5b75666b93238b503aba9fcf32"`);
        await queryRunner.query(`ALTER TABLE "user_vaccine" DROP CONSTRAINT "FK_44987c7db9c6c92fa2e8c310461"`);
        await queryRunner.query(`ALTER TABLE "user_vaccine" DROP CONSTRAINT "FK_cc3e88ea2a405280a5b6d09caba"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP CONSTRAINT "FK_5f7f92a4446c70b2a7ce84994b0"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP CONSTRAINT "FK_512b1bdb900e45a758e2dbb49df"`);
        await queryRunner.query(`ALTER TABLE "userMedications" DROP CONSTRAINT "FK_bdaff5385ad51bcc1af4848a5ed"`);
        await queryRunner.query(`ALTER TABLE "userMedications" DROP CONSTRAINT "FK_cfaf05e2b6d8b08d2f9e5ef1802"`);
        await queryRunner.query(`ALTER TABLE "UserDiseases" DROP CONSTRAINT "FK_c5306c28d972032b84309267399"`);
        await queryRunner.query(`ALTER TABLE "UserDiseases" DROP CONSTRAINT "FK_47fd2b1a5aed5759cbda6b0f6b0"`);
        await queryRunner.query(`ALTER TABLE "userAllergies" DROP CONSTRAINT "FK_de7a18a07034d48eb6b2d5cec26"`);
        await queryRunner.query(`ALTER TABLE "userAllergies" DROP CONSTRAINT "FK_5880801a70cbda1b56a04eb07fe"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP CONSTRAINT "UQ_142ca675cea1a426abac7ba2376"`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "complement" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "city" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "district"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "district" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "number" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "street" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "phone" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "UQ_62069f52ebba471c91de5d59d61"`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "email" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "description" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "sex"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "sex" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "gender" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "medications" DROP CONSTRAINT "UQ_4c71a8a6de0a811702d1ef8d73f"`);
        await queryRunner.query(`ALTER TABLE "medications" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "medications" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "medications" ADD CONSTRAINT "medications_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "medications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "diseases" DROP CONSTRAINT "UQ_293ca0c5bba4f9950f3fb976d33"`);
        await queryRunner.query(`ALTER TABLE "diseases" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "diseases" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "diseases" ADD CONSTRAINT "diseases_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "diseases" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "allergies" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "addressId"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "sex"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "doctorId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "birthDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP CONSTRAINT "UQ_c5b75666b93238b503aba9fcf32"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "physicalActivity"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "drugUser"`);
        await queryRunner.query(`ALTER TABLE "anamnesis" DROP COLUMN "continuousMedication"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "user_surgery" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "address_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "doctor_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "birth_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD CONSTRAINT "anamnesis_user_id_key" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "physical_activity" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "drug_user" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD "continous_medication" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD "surgery_detail_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`DROP TABLE "profileImage"`);
        await queryRunner.query(`DROP TABLE "user_vaccine"`);
        await queryRunner.query(`DROP TABLE "vaccine"`);
        await queryRunner.query(`DROP TABLE "surgery"`);
        await queryRunner.query(`DROP TABLE "userMedications"`);
        await queryRunner.query(`DROP TABLE "UserDiseases"`);
        await queryRunner.query(`DROP TABLE "userAllergies"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "doctors_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "doctors_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_doctor_id_fkey" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anamnesis" ADD CONSTRAINT "anamnesis_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD CONSTRAINT "user_surgery_surgery_detail_id_fkey" FOREIGN KEY ("surgery_detail_id") REFERENCES "surgerys_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD CONSTRAINT "user_surgery_surgery_id_fkey" FOREIGN KEY ("surgery_id") REFERENCES "surgerys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_surgery" ADD CONSTRAINT "user_surgery_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
